//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestArriendosDepa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartamentos()
        {
            this.Caracteristicas = new HashSet<Caracteristicas>();
            this.Condiciones = new HashSet<Condiciones>();
            this.Imagenes = new HashSet<Imagenes>();
            this.Servicios = new HashSet<Servicios>();
        }
    
        public int Id_apartamento { get; set; }
        public string Nombre_apart { get; set; }
        public Nullable<decimal> Precio_apart { get; set; }
        public Nullable<int> Id_usuario_per { get; set; }
        public string Longitud { get; set; }
        public string Latitud { get; set; }
        public Nullable<bool> Estado_apart { get; set; }

        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caracteristicas> Caracteristicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Condiciones> Condiciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagenes> Imagenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios> Servicios { get; set; }
    }
}
