//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestArriendosDepa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristicas
    {
        public int Id_caracteristicas { get; set; }
        public Nullable<int> Id_apartamento_per { get; set; }
        public Nullable<short> N_habitaciones { get; set; }
        public Nullable<bool> ApartamentoCompartido { get; set; }
        public Nullable<bool> Cocina { get; set; }
        public Nullable<bool> Bano_Independiente { get; set; }
        public Nullable<bool> Bano_Compartido { get; set; }
        public Nullable<bool> Ducha { get; set; }
        public Nullable<bool> Amoblado { get; set; }

        public virtual Apartamentos Apartamentos { get; set; }
    }
}
