//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestArriendosDepa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagenes
    {
        public int id_foto { get; set; }
        public Nullable<int> id_apartamentos_per { get; set; }
        public byte[] foto1 { get; set; }
        public byte[] foto2 { get; set; }
        public byte[] foto3 { get; set; }
        public byte[] foto4 { get; set; }
        public byte[] foto5 { get; set; }
        public byte[] foto6 { get; set; }
    
        public virtual Apartamentos Apartamentos { get; set; }
    }
}
