//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestArriendosDepa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Apartamentos = new HashSet<Apartamentos>();
        }
    
        public int Id_usuario { get; set; }
        public string Nombre_usuario { get; set; }
        public string Contrasena_usuario { get; set; }
        public string Correo_usuario { get; set; }
        public string telefono_usuario { get; set; }
        public Nullable<bool> Arrendatario { get; set; }
        public byte[] Foto_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartamentos> Apartamentos { get; set; }
    }
}
