//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestArriendosDepa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condiciones
    {
        public int Id_condicion { get; set; }
        public Nullable<int> Id_apartamento_per { get; set; }
        public Nullable<bool> Permite_Mascotas { get; set; }
        public Nullable<bool> Permite_Fiestas { get; set; }
        public Nullable<bool> Permite_MusicaAltoVolumen { get; set; }
        public Nullable<bool> Permite_Tomar { get; set; }
        public Nullable<bool> Permite_Fumar { get; set; }
    
        public virtual Apartamentos Apartamentos { get; set; }
    }
}
