//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestArriendosDepa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public int Id_servicio { get; set; }
        public int Id_apartamento_per { get; set; }
        public Nullable<bool> Luz { get; set; }
        public Nullable<bool> Agua { get; set; }
        public Nullable<bool> Telefono { get; set; }
        public Nullable<bool> Garage { get; set; }
        public Nullable<bool> Gas { get; set; }
        public Nullable<bool> Desayuno { get; set; }
        public Nullable<bool> Almuerzo { get; set; }
        public Nullable<bool> Merienda { get; set; }
    
        public virtual Apartamentos Apartamentos { get; set; }
    }
}
